### ISSUE TITLE
Ejs 2.0

### ISSUE THREAD

**Issue by Globik** [koajs/ejs#20]
I have marked that ejs have already version great then 2.0. Koa-ejs in dependencies have ejs 1.0. Why? When will the update in plans?

**Comment by kreja** [comment]
I also wonder why..

**Comment by dead-horse** [comment]
[ejs@2](https://github.com/mde/ejs) is totally different with [ejs@1](https://github.com/tj/ejs), I'm not using ejs@2, but PR's are welcome!

**Comment by Globik** [comment]
Why are you not using ejs@2?

**Comment by dead-horse** [comment]
I don't use `ejs` right now. I'm ok for update koa-ejs to use ejs@4 or whatever.
