### ISSUE TITLE
how can i use "await locals.fn.call()"

### ISSUE THREAD

**Issue by witwave** [koajs/ejs#39]
Hi, I need such function like the co-ejs
the co-ejs only support koa1.x but I hope use in koa2
I can write code in ejs 
```
 <% user= await locals.user.get(1) %>
```
thank you

**Comment by dead-horse** [comment]
no, it won't be supported by this middleware, please prepare all the datas before rendering.

**Comment by witwave** [comment]
ok, thanks @dead-horse 
I have it done in ejs
