### ISSUE TITLE
Layout feature does not return layout.ejs

### ISSUE THREAD

**Issue by adriaanvanrossum** [koajs/ejs#51]
Can't get the **layout feature** to work. I have the following files.

File `index.js`

```js
const path = require('path')
const views = require('koa-views')
const Koa = require('koa')
const app = module.exports = new Koa()

app.use(views(path.join(__dirname, '/views'), { extension: 'ejs' }))

const user = { name: { first: 'Tobi', last: 'Holowaychuk' }, species: 'ferret', age: 5 }

app.use(async function(ctx) {
  await ctx.render('user', { user })
})

app.listen(3000)
```

File `views/layout.ejs`

```ejs
<html>
  <head>
    <title>koa ejs</title>
  </head>
  <body>
    <h3>koa ejs</h3>
    <%- body %>
  </body>
</html>
```

File `views/user.ejs`

```ejs
<p><%= user.name.first %> is a <%= user.age %> year old <%= user.species %>.</p>
```

Copied from https://github.com/koajs/examples/blob/master/templates/app.js

Changing `await ctx.render('user', { user })` to `await ctx.render('user', { user, layout: 'layout.ejs' })` also does nothing.

The only result I get is `<p>Tobi is a 5 year old ferret.</p>` (no sign of `layout.ejs`).

**Comment by Runrioter** [comment]
You use 'koa-views not `koa-ejs` ?

**Comment by adriaanvanrossum** [comment]
<img src="https://user-images.githubusercontent.com/1079135/51681966-7fe27f00-1fe6-11e9-94d4-8873c0b9bce8.gif" width="100%">
