### ISSUE TITLE
why set option 'compileDebug' as 'settings.debug && settings.compileDebug'? 

### ISSUE THREAD

**Issue by Magin-CC** [koajs/ejs#53]
koa-ejs/index.js line 96:
```
const fn = ejs.compile(tpl, {
      filename: viewPath,
      _with: settings._with,
      compileDebug: settings.debug && settings.compileDebug,
      debug: settings.debug,
      delimiter: settings.delimiter,
      cache: settings.cache,
      async: settings.async
    });
```
why  set option 'compileDebug' as 'settings.debug && settings.compileDebug' 
 instead of 'settings.compileDebug'?

**Comment by Runrioter** [comment]
Please refer to https://github.com/koajs/ejs/pull/37

CompileDebug works depending on debug.

### References

* https://github.com/mde/ejs/blob/master/lib/ejs.js#L585-L610

**Comment by Magin-CC** [comment]
if I set "debug" and "compileDebug" options both true, console will output a lot of useless infomation.
When I change the code like this:
```
const fn = ejs.compile(tpl, {
      filename: viewPath,
      _with: settings._with,
      compileDebug: settings.compileDebug,
      debug: settings.debug,
      delimiter: settings.delimiter,
      cache: settings.cache,
      async: settings.async
    });
```
and I set 
``
{
  compileDebug: true,
  debug: false,
}
``
I successfully got the stack information.
才看到您也是中国人，在您发送的 pr中提到
> compileDebug works depending on debug.
但在ejs的相关文档中，我并没有找到有提示这个依赖关系的信息，能否烦请提示下这个依赖关系是怎么体现的，因为debug选项输出的信息实在太过冗长而无用了
