### ISSUE TITLE
Not support include with parameters?

### ISSUE THREAD

**Issue by jinwyp** [koajs/ejs#54]
not support    <%- include('user/show', {user: user}); %> ? got error

see  https://ejs.co/#docs , 
support  <%- include('user/show', {user: user}); %>

**Comment by SirWumpus** [comment]
The behaviour of `include path` and `include(path, data)` comes from `ejs` and from a test in my application appears to work.

**Comment by 3imed-jaberi** [comment]
Solved ✅!
